// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protos

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConfigAgentClient is the client API for ConfigAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigAgentClient interface {
}

type configAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigAgentClient(cc grpc.ClientConnInterface) ConfigAgentClient {
	return &configAgentClient{cc}
}

// ConfigAgentServer is the server API for ConfigAgent service.
// All implementations must embed UnimplementedConfigAgentServer
// for forward compatibility
type ConfigAgentServer interface {
	mustEmbedUnimplementedConfigAgentServer()
}

// UnimplementedConfigAgentServer must be embedded to have forward compatible implementations.
type UnimplementedConfigAgentServer struct {
}

func (UnimplementedConfigAgentServer) mustEmbedUnimplementedConfigAgentServer() {}

// UnsafeConfigAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigAgentServer will
// result in compilation errors.
type UnsafeConfigAgentServer interface {
	mustEmbedUnimplementedConfigAgentServer()
}

func RegisterConfigAgentServer(s grpc.ServiceRegistrar, srv ConfigAgentServer) {
	s.RegisterService(&ConfigAgent_ServiceDesc, srv)
}

// ConfigAgent_ServiceDesc is the grpc.ServiceDesc for ConfigAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.ConfigAgent",
	HandlerType: (*ConfigAgentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "oracle/pkg/agents/config_agent/protos/service.proto",
}
