// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Config Agent proto for gRPC communications from controllers.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: oracle/pkg/agents/config_agent/protos/service.proto

package protos

import (
	longrunning "google.golang.org/genproto/googleapis/longrunning"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GsmSecretReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId   string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SecretId    string `protobuf:"bytes,2,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	Version     string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	LastVersion string `protobuf:"bytes,4,opt,name=last_version,json=lastVersion,proto3" json:"last_version,omitempty"`
}

func (x *GsmSecretReference) Reset() {
	*x = GsmSecretReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oracle_pkg_agents_config_agent_protos_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GsmSecretReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GsmSecretReference) ProtoMessage() {}

func (x *GsmSecretReference) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_pkg_agents_config_agent_protos_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GsmSecretReference.ProtoReflect.Descriptor instead.
func (*GsmSecretReference) Descriptor() ([]byte, []int) {
	return file_oracle_pkg_agents_config_agent_protos_service_proto_rawDescGZIP(), []int{0}
}

func (x *GsmSecretReference) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GsmSecretReference) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *GsmSecretReference) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GsmSecretReference) GetLastVersion() string {
	if x != nil {
		return x.LastVersion
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// only being used for plaintext password scenario.
	// GSM doesn't use this field.
	Password             string              `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Privileges           []string            `protobuf:"bytes,3,rep,name=privileges,proto3" json:"privileges,omitempty"`
	PasswordGsmSecretRef *GsmSecretReference `protobuf:"bytes,4,opt,name=password_gsm_secret_ref,json=passwordGsmSecretRef,proto3" json:"password_gsm_secret_ref,omitempty"`
	// only being used for plaintext password scenario.
	// GSM doesn't use this field.
	LastPassword string `protobuf:"bytes,5,opt,name=last_password,json=lastPassword,proto3" json:"last_password,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oracle_pkg_agents_config_agent_protos_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_pkg_agents_config_agent_protos_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_oracle_pkg_agents_config_agent_protos_service_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetPrivileges() []string {
	if x != nil {
		return x.Privileges
	}
	return nil
}

func (x *User) GetPasswordGsmSecretRef() *GsmSecretReference {
	if x != nil {
		return x.PasswordGsmSecretRef
	}
	return nil
}

func (x *User) GetLastPassword() string {
	if x != nil {
		return x.LastPassword
	}
	return ""
}

type DataPumpImportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PdbName  string `protobuf:"bytes,1,opt,name=pdb_name,json=pdbName,proto3" json:"pdb_name,omitempty"`
	DbDomain string `protobuf:"bytes,2,opt,name=db_domain,json=dbDomain,proto3" json:"db_domain,omitempty"`
	// GCS path to input dump file
	GcsPath string `protobuf:"bytes,3,opt,name=gcs_path,json=gcsPath,proto3" json:"gcs_path,omitempty"`
	// GCS path to output log file
	GcsLogPath string    `protobuf:"bytes,4,opt,name=gcs_log_path,json=gcsLogPath,proto3" json:"gcs_log_path,omitempty"`
	LroInput   *LROInput `protobuf:"bytes,5,opt,name=lro_input,json=lroInput,proto3" json:"lro_input,omitempty"`
}

func (x *DataPumpImportRequest) Reset() {
	*x = DataPumpImportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oracle_pkg_agents_config_agent_protos_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataPumpImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPumpImportRequest) ProtoMessage() {}

func (x *DataPumpImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_pkg_agents_config_agent_protos_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPumpImportRequest.ProtoReflect.Descriptor instead.
func (*DataPumpImportRequest) Descriptor() ([]byte, []int) {
	return file_oracle_pkg_agents_config_agent_protos_service_proto_rawDescGZIP(), []int{2}
}

func (x *DataPumpImportRequest) GetPdbName() string {
	if x != nil {
		return x.PdbName
	}
	return ""
}

func (x *DataPumpImportRequest) GetDbDomain() string {
	if x != nil {
		return x.DbDomain
	}
	return ""
}

func (x *DataPumpImportRequest) GetGcsPath() string {
	if x != nil {
		return x.GcsPath
	}
	return ""
}

func (x *DataPumpImportRequest) GetGcsLogPath() string {
	if x != nil {
		return x.GcsLogPath
	}
	return ""
}

func (x *DataPumpImportRequest) GetLroInput() *LROInput {
	if x != nil {
		return x.LroInput
	}
	return nil
}

type DataPumpExportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PdbName       string    `protobuf:"bytes,1,opt,name=pdb_name,json=pdbName,proto3" json:"pdb_name,omitempty"`
	DbDomain      string    `protobuf:"bytes,2,opt,name=db_domain,json=dbDomain,proto3" json:"db_domain,omitempty"`
	ObjectType    string    `protobuf:"bytes,3,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	Objects       string    `protobuf:"bytes,4,opt,name=objects,proto3" json:"objects,omitempty"`
	GcsPath       string    `protobuf:"bytes,5,opt,name=gcs_path,json=gcsPath,proto3" json:"gcs_path,omitempty"`
	GcsLogPath    string    `protobuf:"bytes,6,opt,name=gcs_log_path,json=gcsLogPath,proto3" json:"gcs_log_path,omitempty"`
	LroInput      *LROInput `protobuf:"bytes,7,opt,name=lro_input,json=lroInput,proto3" json:"lro_input,omitempty"`
	FlashbackTime string    `protobuf:"bytes,8,opt,name=flashback_time,json=flashbackTime,proto3" json:"flashback_time,omitempty"`
}

func (x *DataPumpExportRequest) Reset() {
	*x = DataPumpExportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oracle_pkg_agents_config_agent_protos_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataPumpExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPumpExportRequest) ProtoMessage() {}

func (x *DataPumpExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_pkg_agents_config_agent_protos_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPumpExportRequest.ProtoReflect.Descriptor instead.
func (*DataPumpExportRequest) Descriptor() ([]byte, []int) {
	return file_oracle_pkg_agents_config_agent_protos_service_proto_rawDescGZIP(), []int{3}
}

func (x *DataPumpExportRequest) GetPdbName() string {
	if x != nil {
		return x.PdbName
	}
	return ""
}

func (x *DataPumpExportRequest) GetDbDomain() string {
	if x != nil {
		return x.DbDomain
	}
	return ""
}

func (x *DataPumpExportRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *DataPumpExportRequest) GetObjects() string {
	if x != nil {
		return x.Objects
	}
	return ""
}

func (x *DataPumpExportRequest) GetGcsPath() string {
	if x != nil {
		return x.GcsPath
	}
	return ""
}

func (x *DataPumpExportRequest) GetGcsLogPath() string {
	if x != nil {
		return x.GcsLogPath
	}
	return ""
}

func (x *DataPumpExportRequest) GetLroInput() *LROInput {
	if x != nil {
		return x.LroInput
	}
	return nil
}

func (x *DataPumpExportRequest) GetFlashbackTime() string {
	if x != nil {
		return x.FlashbackTime
	}
	return ""
}

// LROInput is a common part of input requests for all Async operations.
type LROInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationId string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
}

func (x *LROInput) Reset() {
	*x = LROInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oracle_pkg_agents_config_agent_protos_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LROInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LROInput) ProtoMessage() {}

func (x *LROInput) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_pkg_agents_config_agent_protos_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LROInput.ProtoReflect.Descriptor instead.
func (*LROInput) Descriptor() ([]byte, []int) {
	return file_oracle_pkg_agents_config_agent_protos_service_proto_rawDescGZIP(), []int{4}
}

func (x *LROInput) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetParameterTypeValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *GetParameterTypeValueRequest) Reset() {
	*x = GetParameterTypeValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oracle_pkg_agents_config_agent_protos_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetParameterTypeValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParameterTypeValueRequest) ProtoMessage() {}

func (x *GetParameterTypeValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_pkg_agents_config_agent_protos_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParameterTypeValueRequest.ProtoReflect.Descriptor instead.
func (*GetParameterTypeValueRequest) Descriptor() ([]byte, []int) {
	return file_oracle_pkg_agents_config_agent_protos_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetParameterTypeValueRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type GetParameterTypeValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Types  []string `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	Values []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *GetParameterTypeValueResponse) Reset() {
	*x = GetParameterTypeValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oracle_pkg_agents_config_agent_protos_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetParameterTypeValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParameterTypeValueResponse) ProtoMessage() {}

func (x *GetParameterTypeValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_pkg_agents_config_agent_protos_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParameterTypeValueResponse.ProtoReflect.Descriptor instead.
func (*GetParameterTypeValueResponse) Descriptor() ([]byte, []int) {
	return file_oracle_pkg_agents_config_agent_protos_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetParameterTypeValueResponse) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *GetParameterTypeValueResponse) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_oracle_pkg_agents_config_agent_protos_service_proto protoreflect.FileDescriptor

var file_oracle_pkg_agents_config_agent_protos_service_proto_rawDesc = []byte{
	0x0a, 0x33, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x23, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x6c, 0x6f, 0x6e, 0x67, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e,
	0x67, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x8d, 0x01, 0x0a, 0x12, 0x47, 0x73, 0x6d, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x21, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0xce, 0x01, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x70,
	0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x73, 0x12, 0x51, 0x0a, 0x17, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x67, 0x73, 0x6d, 0x5f, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x73, 0x6d, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x14, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x47, 0x73, 0x6d, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x66, 0x12, 0x23,
	0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0xbb, 0x01, 0x0a, 0x15, 0x44, 0x61, 0x74, 0x61, 0x50, 0x75, 0x6d, 0x70,
	0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x70, 0x64, 0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x70, 0x64, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x62, 0x5f, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x62, 0x44,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x63, 0x73, 0x5f, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x63, 0x73, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x20, 0x0a, 0x0c, 0x67, 0x63, 0x73, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x63, 0x73, 0x4c, 0x6f, 0x67, 0x50, 0x61,
	0x74, 0x68, 0x12, 0x2d, 0x0a, 0x09, 0x6c, 0x72, 0x6f, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c,
	0x52, 0x4f, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x08, 0x6c, 0x72, 0x6f, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x22, 0x9d, 0x02, 0x0a, 0x15, 0x44, 0x61, 0x74, 0x61, 0x50, 0x75, 0x6d, 0x70, 0x45, 0x78,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x70,
	0x64, 0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70,
	0x64, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x62, 0x5f, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x62, 0x44, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x19,
	0x0a, 0x08, 0x67, 0x63, 0x73, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x67, 0x63, 0x73, 0x50, 0x61, 0x74, 0x68, 0x12, 0x20, 0x0a, 0x0c, 0x67, 0x63, 0x73,
	0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x67, 0x63, 0x73, 0x4c, 0x6f, 0x67, 0x50, 0x61, 0x74, 0x68, 0x12, 0x2d, 0x0a, 0x09, 0x6c,
	0x72, 0x6f, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x52, 0x4f, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x52, 0x08, 0x6c, 0x72, 0x6f, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x6c,
	0x61, 0x73, 0x68, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x2d, 0x0a, 0x08, 0x4c, 0x52, 0x4f, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x21, 0x0a,
	0x0c, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x22, 0x32, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x6b, 0x65, 0x79, 0x73, 0x22, 0x4d, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x32, 0x95, 0x02, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x12, 0x4e, 0x0a, 0x0e, 0x44, 0x61, 0x74, 0x61, 0x50, 0x75, 0x6d, 0x70, 0x49,
	0x6d, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x50, 0x75, 0x6d, 0x70, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x6c, 0x6f,
	0x6e, 0x67, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x4e, 0x0a, 0x0e, 0x44, 0x61, 0x74, 0x61, 0x50, 0x75, 0x6d, 0x70, 0x45,
	0x78, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x50, 0x75, 0x6d, 0x70, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x6c, 0x6f,
	0x6e, 0x67, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x66, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x24, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x65, 0x5a, 0x63, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x43, 0x6c, 0x6f, 0x75, 0x64, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x65, 0x6c,
	0x63, 0x61, 0x72, 0x72, 0x6f, 0x2d, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x2d, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_oracle_pkg_agents_config_agent_protos_service_proto_rawDescOnce sync.Once
	file_oracle_pkg_agents_config_agent_protos_service_proto_rawDescData = file_oracle_pkg_agents_config_agent_protos_service_proto_rawDesc
)

func file_oracle_pkg_agents_config_agent_protos_service_proto_rawDescGZIP() []byte {
	file_oracle_pkg_agents_config_agent_protos_service_proto_rawDescOnce.Do(func() {
		file_oracle_pkg_agents_config_agent_protos_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_oracle_pkg_agents_config_agent_protos_service_proto_rawDescData)
	})
	return file_oracle_pkg_agents_config_agent_protos_service_proto_rawDescData
}

var file_oracle_pkg_agents_config_agent_protos_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_oracle_pkg_agents_config_agent_protos_service_proto_goTypes = []interface{}{
	(*GsmSecretReference)(nil),            // 0: protos.GsmSecretReference
	(*User)(nil),                          // 1: protos.User
	(*DataPumpImportRequest)(nil),         // 2: protos.DataPumpImportRequest
	(*DataPumpExportRequest)(nil),         // 3: protos.DataPumpExportRequest
	(*LROInput)(nil),                      // 4: protos.LROInput
	(*GetParameterTypeValueRequest)(nil),  // 5: protos.GetParameterTypeValueRequest
	(*GetParameterTypeValueResponse)(nil), // 6: protos.GetParameterTypeValueResponse
	(*longrunning.Operation)(nil),         // 7: google.longrunning.Operation
}
var file_oracle_pkg_agents_config_agent_protos_service_proto_depIdxs = []int32{
	0, // 0: protos.User.password_gsm_secret_ref:type_name -> protos.GsmSecretReference
	4, // 1: protos.DataPumpImportRequest.lro_input:type_name -> protos.LROInput
	4, // 2: protos.DataPumpExportRequest.lro_input:type_name -> protos.LROInput
	2, // 3: protos.ConfigAgent.DataPumpImport:input_type -> protos.DataPumpImportRequest
	3, // 4: protos.ConfigAgent.DataPumpExport:input_type -> protos.DataPumpExportRequest
	5, // 5: protos.ConfigAgent.GetParameterTypeValue:input_type -> protos.GetParameterTypeValueRequest
	7, // 6: protos.ConfigAgent.DataPumpImport:output_type -> google.longrunning.Operation
	7, // 7: protos.ConfigAgent.DataPumpExport:output_type -> google.longrunning.Operation
	6, // 8: protos.ConfigAgent.GetParameterTypeValue:output_type -> protos.GetParameterTypeValueResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_oracle_pkg_agents_config_agent_protos_service_proto_init() }
func file_oracle_pkg_agents_config_agent_protos_service_proto_init() {
	if File_oracle_pkg_agents_config_agent_protos_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_oracle_pkg_agents_config_agent_protos_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GsmSecretReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oracle_pkg_agents_config_agent_protos_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oracle_pkg_agents_config_agent_protos_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataPumpImportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oracle_pkg_agents_config_agent_protos_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataPumpExportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oracle_pkg_agents_config_agent_protos_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LROInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oracle_pkg_agents_config_agent_protos_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetParameterTypeValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oracle_pkg_agents_config_agent_protos_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetParameterTypeValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_oracle_pkg_agents_config_agent_protos_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oracle_pkg_agents_config_agent_protos_service_proto_goTypes,
		DependencyIndexes: file_oracle_pkg_agents_config_agent_protos_service_proto_depIdxs,
		MessageInfos:      file_oracle_pkg_agents_config_agent_protos_service_proto_msgTypes,
	}.Build()
	File_oracle_pkg_agents_config_agent_protos_service_proto = out.File
	file_oracle_pkg_agents_config_agent_protos_service_proto_rawDesc = nil
	file_oracle_pkg_agents_config_agent_protos_service_proto_goTypes = nil
	file_oracle_pkg_agents_config_agent_protos_service_proto_depIdxs = nil
}
