// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PITRAgentClient is the client API for PITRAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PITRAgentClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type pITRAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewPITRAgentClient(cc grpc.ClientConnInterface) PITRAgentClient {
	return &pITRAgentClient{cc}
}

func (c *pITRAgentClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/protos.PITRAgent/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PITRAgentServer is the server API for PITRAgent service.
// All implementations must embed UnimplementedPITRAgentServer
// for forward compatibility
type PITRAgentServer interface {
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedPITRAgentServer()
}

// UnimplementedPITRAgentServer must be embedded to have forward compatible implementations.
type UnimplementedPITRAgentServer struct {
}

func (UnimplementedPITRAgentServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedPITRAgentServer) mustEmbedUnimplementedPITRAgentServer() {}

// UnsafePITRAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PITRAgentServer will
// result in compilation errors.
type UnsafePITRAgentServer interface {
	mustEmbedUnimplementedPITRAgentServer()
}

func RegisterPITRAgentServer(s grpc.ServiceRegistrar, srv PITRAgentServer) {
	s.RegisterService(&PITRAgent_ServiceDesc, srv)
}

func _PITRAgent_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PITRAgentServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.PITRAgent/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PITRAgentServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PITRAgent_ServiceDesc is the grpc.ServiceDesc for PITRAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PITRAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.PITRAgent",
	HandlerType: (*PITRAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _PITRAgent_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oracle/pkg/agents/pitr/proto/service.proto",
}
