# permissions for end users to view backupschedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backupschedule-viewer-role
rules:
- apiGroups:
  - oracle.db.anthosapis.com
  resources:
  - backupschedules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oracle.db.anthosapis.com
  resources:
  - backupschedules/status
  verbs:
  - get
