# permissions to do viewer configs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: config-viewer-role
rules:
- apiGroups:
  - oracle.db.anthosapis.com
  resources:
  - configs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oracle.db.anthosapis.com
  resources:
  - configs/status
  verbs:
  - get
