# permissions for end users to view cronanythings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronanything-viewer-role
rules:
- apiGroups:
  - oracle.db.anthosapis.com
  resources:
  - cronanythings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oracle.db.anthosapis.com
  resources:
  - cronanythings/status
  verbs:
  - get
