# permissions to do edit databases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: database-editor-role
rules:
- apiGroups:
  - oracle.db.anthosapis.com
  resources:
  - databases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oracle.db.anthosapis.com
  resources:
  - databases/status
  verbs:
  - get
  - patch
  - update
