# permissions to do viewer exports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: export-viewer-role
rules:
- apiGroups:
  - oracle.db.anthosapis.com
  resources:
  - exports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oracle.db.anthosapis.com
  resources:
  - exports/status
  verbs:
  - get
