# permissions to do edit imports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: import-editor-role
rules:
- apiGroups:
  - oracle.db.anthosapis.com
  resources:
  - imports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oracle.db.anthosapis.com
  resources:
  - imports/status
  verbs:
  - get
  - patch
  - update
