# permissions to do viewer imports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: import-viewer-role
rules:
- apiGroups:
  - oracle.db.anthosapis.com
  resources:
  - imports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oracle.db.anthosapis.com
  resources:
  - imports/status
  verbs:
  - get
