# permissions for end users to view pitrs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pitr-viewer-role
rules:
- apiGroups:
  - oracle.db.anthosapis.com
  resources:
  - pitrs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oracle.db.anthosapis.com
  resources:
  - pitrs/status
  verbs:
  - get
