# permissions for end users to edit pitrs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pitr-editor-role
rules:
- apiGroups:
  - oracle.db.anthosapis.com
  resources:
  - pitrs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oracle.db.anthosapis.com
  resources:
  - pitrs/status
  verbs:
  - get
