#!/bin/bash

echo "PROW_IMAGE_REPO ${PROW_IMAGE_REPO}"
echo "PROW_IMAGE_TAG ${PROW_IMAGE_TAG}"
echo "PROW_PROJECT ${PROW_PROJECT}"
echo "PROW_CLUSTER ${PROW_CLUSTER}"
echo "PROW_CLUSTER_ZONE ${PROW_CLUSTER_ZONE}"
