apiVersion: oracle.db.anthosapis.com/v1alpha1
kind: Config
metadata:
  name: config
spec:
  platform: "Kind"
  storageClass: "csi-hostpath-sc"
  volumeSnapshotClass: "csi-hostpath-snapclass"
  images:
    service: "localhost:5000/oracle-12.2-ee-seeded-mydb:latest"
    dbinit: "localhost:5000/oracle.db.anthosapis.com/dbinit:latest"
    logging_sidecar: "localhost:5000/oracle.db.anthosapis.com/loggingsidecar:latest"
    monitoring: "localhost:5000/oracle.db.anthosapis.com/monitoring:latest"
