apiVersion: oracle.db.anthosapis.com/v1alpha1
kind: Instance
metadata:
  name: mydb
spec:
  type: Oracle
  version: "19.3"
  edition: Enterprise
  dbDomain: "gke"
  disks:
  - name: DataDisk
    size: 45Gi
    storageClass: "standard-rwo"
  - name: LogDisk
    size: 55Gi
    storageClass: "standard-rwo"
  services:
    Backup: true
    Monitoring: true
    Logging: true
  sourceCidrRanges: [ 0.0.0.0/0 ]
  images:
    # Replace below with the actual URIs hosting the service agent images.
    service: "gcr.io/${PROJECT_ID}/oracle-database-images/oracle-19.3-ee-seeded-${DB}"
  cdbName: ${DB}
  databaseResources:
    requests:
      memory: 4.0Gi
  parameters:
    cpu_count: "4"
    processes: "1800"
    sga_max_size: "7900M"
  maintenanceWindow:
    timeRanges:
    - start: "2021-01-01T00:00:00Z"
      duration: "87660h" # good till 2031