apiVersion: oracle.db.anthosapis.com/v1alpha1
kind: Config
metadata:
  name: config
spec:
  platform: "Kind"
  storageClass: "csi-hostpath-sc"
  volumeSnapshotClass: "csi-hostpath-snapclass"
  images:
    service: "gcr.io/oracle-database-images/oracle-12.2-ee-seeded-mydb:kind"
    config: "gcr.io/oracle.db.anthosapis.com/configagent:kind"
    dbinit: "gcr.io/oracle.db.anthosapis.com/dbinit:kind"
    logging_sidecar: "gcr.io/oracle.db.anthosapis.com/loggingsidecar:kind"
    monitoring: "gcr.io/oracle.db.anthosapis.com/monitoring:kind"
