# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/oracle.db.anthosapis.com_instances.yaml
- bases/oracle.db.anthosapis.com_databases.yaml
- bases/oracle.db.anthosapis.com_backups.yaml
- bases/oracle.db.anthosapis.com_exports.yaml
- bases/oracle.db.anthosapis.com_configs.yaml
- bases/oracle.db.anthosapis.com_releases.yaml
- bases/oracle.db.anthosapis.com_imports.yaml
- bases/oracle.db.anthosapis.com_cronanythings.yaml
- bases/oracle.db.anthosapis.com_backupschedules.yaml
- bases/oracle.db.anthosapis.com_pitrs.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_instances.yaml
#- patches/webhook_in_databases.yaml
#- patches/webhook_in_backups.yaml
#- patches/webhook_in_exports.yaml
#- patches/webhook_in_configs.yaml
#- patches/webhook_in_releases.yaml
#- patches/webhook_in_imports.yaml
#- patches/webhook_in_cronanythings.yaml
#- patches/webhook_in_backupschedules.yaml
#- patches/webhook_in_pitrs.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_instances.yaml
#- patches/cainjection_in_databases.yaml
#- patches/cainjection_in_backups.yaml
#- patches/cainjection_in_exports.yaml
#- patches/cainjection_in_configs.yaml
#- patches/cainjection_in_releases.yaml
#- patches/cainjection_in_imports.yaml
#- patches/cainjection_in_cronanythings.yaml
#- patches/cainjection_in_backupschedules.yaml
#- patches/cainjection_in_pitrs.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
